opendatahub-io/model-registry-operator

.github/workflows/auto-add-issue-to-project.yml, .github/workflows/build-image-main.yml, .github/workflows/build-image-pr.yml, .github/workflows/build.yml, Makefile, README.md, config/manager/kustomization.yaml, config/manager/manager.yaml, config/samples/postgres-db.yaml, internal/controller/modelregistry_controller.go, scripts/build_deploy.sh
Added actions for:
1. Build and test on pull-request
2. Build image for pull requests
3. Build and push images on main push
Verified image build scripts and makefile locally.
=> Add github actions, fixes #12

Makefile, internal/controller/modelregistry_controller_test.go
Copies images from params.env to manager.yaml and defaults.go
Fixes #RHOAIENG-3424
Tested locally by changing params.env image versions and verified that the images were updated in other locations.
=> fix: sync images from params.env, fixes #RHOAIENG-3424

config/manager/manager.yaml, config/overlays/odh/params.env, internal/controller/config/defaults.go
=> chore: change release image versions

Makefile, config/manager/manager.yaml, config/overlays/odh/params.env, internal/controller/config/defaults.go
Change mlmd image to quay.io/opendatahub/mlmd-grpc-server:latest
Fixes RHOAIENG-5111
Tested manually in Istio based model registry operator environment. 
Tested with CI using GH actions.
=> fix: change mlmd image to use odh mlmd build, fixes RHOAIENG-5111

README.md
Cleanup README for enabling routes for non-istio model registry and it's service verification instructions
Fixes RHOAIENG-5156
=> chore: cleanup README for non-istio service verification instructions, fixes RHOAIENG-5156

Dockerfile
This commit updates ubi-minimal:8.9 to ubi-minimal:latest
=> This commit updates ubi-minimal:8.9 to ubi-minimal:latest

api/v1alpha1/modelregistry_webhook.go, config/overlays/odh/kustomization.yaml, config/overlays/odh/patches/manager_webhook_patch.yaml, config/overlays/odh/patches/mutatingwh_cainjection_patch.yaml, config/overlays/odh/patches/validatingwh_cainjection_patch.yaml, config/overlays/odh/patches/webhook_in_modelregistries.yaml, config/overlays/odh/patches/webhook_service_patch.yaml, config/overlays/odh/patches/webhookcainjection_patch.yaml, config/overlays/odh/replacements.yaml, config/webhook/kustomization.yaml, config/webhook/manifests.yaml, config/webhook/service.yaml
Add support for mutating and validating webhooks
Use OpenShift serving certs for ODH model registry webhooks
Fixes #RHOAIENG-906
Applied odh overlay to local cluster to validate that webhooks work
=> feat: add support for mutating and validating webhooks, fixes #RHOAIENG-906

config/samples/mysql/mysql-db.yaml, config/samples/postgres/postgres-db.yaml
Add labels to DB sample resources
Fixes RHOAIENG-11363
Verified labels in DB resources when using MR sample. Verified filtering resources using DB resource labels.
=> feat: add labels to DB sample resources, fixes RHOAIENG-11363

internal/controller/modelregistry_controller.go
Add unexpected reconcile errors to false Available status in MR cr
This handles errors received while looking up dependent k8s resources, e.g. Istio resources, or errors from Istio validation when creating MR istio resources. 
Fixes RHOAIENG-10027
Manually tested by setting the property `istioIngress: bad-ingressgateway`, which results in the error status:
```yaml
- lastTransitionTime: "2024-08-22T23:48:22Z"
message: 'unexpected reconcile error: missing unique ingress gateway service with labels map[istio:bad-ingressgateway], found 0 services'
reason: DeploymentUnavailable
status: "False"
type: Available
```
=> feat: add unexpected reconcile errors to false Available status in MR cr, fixes RHOAIENG-10027

api/v1alpha1/modelregistry_webhook.go, api/v1alpha1/webhook_suite_test.go
Refactor validating webhook to check for unique registry names
Fixes RHOAIENG-13171
WIP
Tested locally, working on adding unit test for refactored webhook.
=> fix: refactor validating webhook to check for unique registry names, fixes RHOAIENG-13171

config/component_metadata.yaml
Add component_metadata.yaml to describe component dependencies
Fixes RHOAIENG-15496
No tests within MR operator. ODH operator will add tests in the future to ensure components provide this file.
=> feat: add component_metadata.yaml to describe component dependencies, fixes RHOAIENG-15496

.github/workflows/build-image-pr.yml, .github/workflows/build.yml, Dockerfile, Makefile, go.mod
=> fix: bump go version to 1.22

config/component_metadata.yaml
bump mr component version in config/component_metadata.yaml
Changes in yaml description file only.
=> fix: bump mr component version

docs/how-to-use-ui.md, docs/install.md
RHOAIENG-16591 Document mysql_native_password need for model registry service connection
per existing docs/tutorial.
=> docs: RHOAIENG-16591 note on mysql_native_password

config/component_metadata.yaml, config/manager/manager.yaml, config/overlays/odh/params.env, internal/controller/config/defaults.go
analogous to https://github.com/opendatahub-io/model-registry-operator/pull/110, https://github.com/opendatahub-io/model-registry-operator/pull/201 proceeding to merge for releasing 0.2.15
=> chore: change release image versions v0.2.15

config/component_metadata.yaml, config/manager/manager.yaml, config/overlays/odh/params.env, internal/controller/config/defaults.go
=> chore: change release image versions v0.2.16

config/component_metadata.yaml, config/manager/manager.yaml, config/overlays/odh/params.env, internal/controller/config/defaults.go
analogous to https://github.com/opendatahub-io/model-registry-operator/pull/110, https://github.com/opendatahub-io/model-registry-operator/pull/201 proceeding to merge for releasing 0.2.17
=> chore: change release image versions v0.2.17

config/component_metadata.yaml, config/manager/manager.yaml, config/overlays/odh/params.env, internal/controller/config/defaults.go
=> chore: change release image versions v0.2.18

config/component_metadata.yaml, config/manager/manager.yaml, config/overlays/odh/params.env, internal/controller/config/defaults.go
=> chore: change release image versions v0.2.19

.tekton/odh-model-registry-operator-push.yaml, config/overlays/odh/params.env
Prepare the branch for the patch release `v0.2.20a-odh`
=> feat: prepare release v0.2.20a-odh

config/component_metadata.yaml, config/manager/manager.yaml, config/overlays/odh/params.env, internal/controller/config/defaults.go
analogous to https://github.com/opendatahub-io/model-registry-operator/pull/110, https://github.com/opendatahub-io/model-registry-operator/pull/201 proceeding to merge for releasing 0.2.21
=> chore: change release image versions v0.2.21
