opendatahub-io/model-registry-operator

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/tracker.yml, .github/dependabot.yml, .github/pull_request_template.md
Added files for github issue templates, dependabot config and github PR template
=> Add github issue templates, dependabot config and PR template

config/samples/postgres-db.yaml
PostgreSQL data directory has changed in the latest version from `/var/lib/pgsql/data` to `/var/lib/postgresql/data`. The path needs to be fixed in sample DB manifest to save data in the PVC.
=> Fix postgresql data directory in sample DB manifest

.github/workflows/build.yml
Controller requires go version 1.20
=> Fix go version in actions to 1.20.10

internal/controller/config/defaults.go, internal/controller/config/templates/deployment.yaml.tmpl, internal/controller/config/templates/service.yaml.tmpl, internal/controller/config/templates/serviceaccount.yaml.tmpl, internal/controller/modelregistry_controller.go, internal/controller/modelregistry_controller_test.go, internal/controller/suite_test.go
Added unit test `modelregistry_controller_test.go` for controller reconcile to test that service k8s resources are successfully created. 
Unit test run using `make test` passes.
=> Add unit test for controller reconcile, fixes #17

internal/controller/config/templates/deployment.yaml.tmpl
Resolves #26
Without explicit params the deployed MR would try to connect to MLMD gRPC to localhost:8081
See: https://github.com/opendatahub-io/model-registry/blob/04aa36605d43a9884b06fb9cd68ce46a14b6b717/cmd/proxy.go#L77-L80
Now connects to port 9090 accounting for template values:
Ad-hoc built operator in another quay organization and deployed with this change.
Deploys as expected:
NOTE: notice the `I1113 10:05:11.181255 1 proxy.go:34] MLMD server localhost:9090` line, to connect to the expected defaults.
Manually created OCP Route (accounting for #19 by defining it manually):
Then can be used:
=> Explicit model-registry proxy MLMD gRPC port param

config/samples/postgres-db.yaml
Resolves #20
Maintain `PGDATA` as required on OCP and other K8s clusters.
Showing the issue:
```
initdb: error: directory "/var/lib/postgresql/data" exists but is not empty
initdb: detail: It contains a lost+found directory, perhaps due to it being a mount point.
initdb: hint: Using a mount point directly as the data directory is not recommended.
Create a subdirectory under the mount point.
```
With this fix applied (`kubectl apply -f config/samples/postgres-db.yaml`):
=> Maintain PGDATA for postresql on OCP

api/v1alpha1/modelregistry_types.go, api/v1alpha1/modelregistry_webhook.go, cmd/main.go, config/crd/bases/modelregistry.opendatahub.io_modelregistries.yaml, config/samples/modelregistry_v1alpha1_modelregistry.yaml, go.mod, go.sum, internal/controller/config/defaults.go, internal/controller/config/templates/http-route.yaml.tmpl, internal/controller/modelregistry_controller.go, internal/controller/modelregistry_controller_test.go
Added template and logic to create an OpenShift Route only if the controller is running in an OpenShift cluster. 
Fixes #19
Tested by setting the rest spec flag `ServiceRoute` to enabled in sample model registry manually to verify that Route is created.
Tested Route by using curl against the hostname created by OpenShift.
=> Add support for creating a Route for ModelRegistry http REST service, fixes #19

config/rbac/role.yaml, internal/controller/modelregistry_controller.go
Permissions is missing rbac role for Route, 
fixes #30
Deployed after enabling route permissions to verify that the watch permission errors go away.
=> Fix missing rbac role for Route, fixes #30

.github/workflows/build-image-pr.yml, Makefile
Added kind integration test to build-image-pr.yaml workflow.
It creates a Kind cluster, deploys operator image built for the PR in the test cluster, and checks that it can create a model registry from sample model registry CR.
Fixes #41
Tested GH action locally using [act](https://github.com/nektos/act).
=> chore: Add kind integration test, fixes #41

Dockerfile
Fixes https://issues.redhat.com/browse/RHOAIENG-2267
Rely on UBI base images for the container image generation as other operators/controllers are doing, e.g., [opendatahub-operator](https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/Dockerfiles/Dockerfile) or [odh-model-controller](https://github.com/opendatahub-io/odh-model-controller/blob/main/Containerfile).
Note that this change is required for production builds, therefore I would keep the differences as small as possible.
Tested locally by running:
```bash
docker build -t model-registry-operator:latest -f Dockerfile .
```
=> [RHOAIENG-2267] Use ubi8 base images for Dockerfile

config/manager/manager.yaml, config/overlays/odh/params.env, internal/controller/config/defaults.go, internal/controller/modelregistry_controller_test.go
Updated params.env image versions for operator and model-registry from quay.io.
CI job will test building an image and deploying it in a kind cluster.
=> chore: change release image versions

internal/controller/config/defaults.go, internal/controller/config/defaults_test.go, internal/controller/modelregistry_controller_test.go
Added viper.AutomaticEnv() in defaults.go init() to use env variables
Fixes #RHOAIENG-3427
Added unit test to verify GetStringConfigWithDefault uses env variables.
=> fix: init viper to use env variables, fixes #RHOAIENG-3427

Makefile, config/overlays/odh/kustomization.yaml
Enables default kubebuilder prometheus config in config/crd/default/kustomization.yaml
Fixes #66
=> Enable kubebuilder prometheus config in odh overlay, fixes #66

internal/controller/config/templates/deployment.yaml.tmpl
Disable Istio injection in deployment for non-istio model registries by setting label `sidecar.istio.io/inject` to `false`
Fixes RHOAIENG-5154
Tested by creating a non-istio model registry in an istio servicemeshmember namespace.
=> fix: disable Istio injection in deployment for non-istio model registries, fixes RHOAIENG-5154

internal/controller/modelregistry_controller.go
When istio config is missing, delete all istio resources
Fixes RHOAIENG-5158
=> fix: delete istio resources when istio is disabled, fixes RHOAIENG-5158

internal/controller/config/templates/deployment.yaml.tmpl
Disable Istio annotations in deployment for non-istio model registries
Fixes RHOAIENG-5154
Tested locally by creating istio and non-istio samples.
=> fix: disable Istio annotations in deployment for non-istio model registries, fixes RHOAIENG-5154

README.md, api/v1alpha1/modelregistry_types.go, api/v1alpha1/modelregistry_webhook.go, config/crd/bases/modelregistry.opendatahub.io_modelregistries.yaml, config/rbac/role.yaml, config/samples/istio/components/istio_modelregistry.yaml, internal/controller/config/templates/istio/gateway-route.yaml.tmpl, internal/controller/modelregistry_controller.go
Create gateway service routes in model registry operator. This is required because OpenShift Service Mesh gateway route creation is deprecated and will be removed in coming versions. 
Fixes RHOAIENG-5559
Tested locally by verifying that gateway routes are created automatically without having Istio Service Mesh gateway route creation enabled.
=> fix: create gateway service routes in model registry operator, fixes RHOAIENG-5559

internal/controller/modelregistry_controller.go
Add missing watches for Role and RoleBinding by using controller builder.Owns()
Fixes RHOAIENG-6601
Verified locally, verified by CI tests.
=> fix: add missing watches by using controller builder.Owns(), fixes RHOAIENG-6601

Makefile, README.md, config/samples/postgres/postgres-db.yaml, config/samples/secure-db/components/kustomization.yaml, config/samples/secure-db/components/model-registry-db-secrets.yaml, config/samples/secure-db/components/mysql/kustomization.yaml, config/samples/secure-db/components/mysql/mysql-ssl-args.yaml, config/samples/secure-db/components/mysql/secure_mysql_modelregistry.yaml, config/samples/secure-db/mysql-tls/kustomization.yaml, config/samples/secure-db/mysql/kustomization.yaml, scripts/generate_certs.sh
Added secure mysql db samples without and with istio tls
Fixes RHOAIENG-5436
Fixes RHOAIENG-6713
Tested samples manually, by first creating the DB cert using `make certificates` and then the appropriate `kubectl apply -k` command.
=> fix: add secure mysql db samples, fixes RHOAIENG-5436

api/v1alpha1/modelregistry_types.go, config/crd/bases/modelregistry.opendatahub.io_modelregistries.yaml, internal/controller/modelregistry_controller.go, internal/controller/modelregistry_controller_status.go
Added conditions IstioAvailable and GatewayAvailable to model registry custom resource for istio and gateway status
Also added printer columns for all conditions in kubernetes cli output and -o wide format
fixes RHOAIENG-5226
Tested manually for all mr samples and changes from one sample type to another
Tested manually that it detects missing ServiceMeshMember configuration which causes Istio proxy to not be injected
=> feat: add conditions to custom resource for istio and gateway status, add printer columns for all conditions, fixes RHOAIENG-5226

api/v1alpha1/modelregistry_types.go, config/crd/bases/modelregistry.opendatahub.io_modelregistries.yaml, internal/controller/modelregistry_controller.go, internal/controller/modelregistry_controller_status.go
Added logic to modelregistry_controller_status to get detailed error messages from deployment and pod status for various error use cases
Operator defaults to generic error messages to avoid ignoring errors when specific errors cannot be found in status conditions
Fixes RHOAIENG-8789
Deployment was broken by setting grpc image property to bad:image in model registry spec manually, which causes the deployment to fail gradually as it tries to resolve the missing image condition. The operator gracefully handles the evolving status changes.
=> feat: add detailed error messages from deployment and pod status, fixes RHOAIENG-8789

internal/controller/modelregistry_controller.go, internal/controller/modelregistry_controller_status.go
Add watch for gateway routes. Since these are created by operator, it needs to look for changes to routes to ensure the haven't been externally broken
Fixes RHOAIENG-8897
Tested by manually trying to delete the routes
=> feat: add watch for gateway routes to handle user changes to operator created routes, fixes RHOAIENG-8897

internal/controller/modelregistry_controller_status.go, internal/controller/modelregistry_controller_test.go
Start by assuming that DeploymentAvailable condition is missing/not available, i.e. only set MR status to available when deployment is actually available.
This can happen when the Deployment is initialized in K8s but without any of it's conditions set.
Fixes RHOAIENG-9184
Tested locally by waiting for availability right away by using the command:
```
kubectl apply -k config/samples/postgres/; kubectl wait --for=condition=Available=true modelregistries/modelregistry-sample --timeout=5m
```
=> fix: start condition check for deployment with the assumption that it is not available, fixes RHOAIENG-9184

.gitleaks.toml, config/samples/mysql/mysql-db.yaml, config/samples/postgres/postgres-db.yaml
This commit will allow the test credentials for the postgress and mysql databases to pass prodsec scanning.
It should stop emails being received by the team informing us we have a potential data leak because of test credentials.
Instructions on how should be done are found [here](https://source.redhat.com/departments/it/it-information-security/wiki/pattern_distribution_server#handling-false-positives).
Added '# notsecret tag to database-password and database-user lines in both postgres-db.yaml and mysql-db.yaml
Added a .gitleaks.toml file to allow prodsec to scan all previous commits.
It has been tested locally using gitleaks cli.
=> Update db test secrets

internal/controller/modelregistry_controller.go, internal/controller/modelregistry_controller_test.go
Copy model registry display name and desription annotations only to model registry service. 
This will let odh dashboard read them from the service itself instead of requiring get/list access to model registry custom resource.
Fixes RHOAIENG-9376
=> feat: copy model registry display name and description annotations to model registry service, fixes RHOAIENG-9376

Makefile, README.md, api/v1alpha1/modelregistry_types.go, cmd/main.go, config/crd/bases/modelregistry.opendatahub.io_modelregistries.yaml, config/manager/manager.yaml, config/rbac/role.yaml, config/samples/istio/components/istio.env, internal/controller/modelregistry_controller.go, scripts/generate_certs.sh
Set domain automatically in Openshift cluster either from an env variable in the operator, or from Openshift cluster if available
Fixes RHOAIENG-5123
The default istio.env config file now has an empty DOMAIN parameter
=> feat: set domain automatically in Openshift cluster, fixes RHOAIENG-5123

internal/controller/modelregistry_controller.go
=> chore: ensure functions use inherited context

internal/controller/config/templates/service.yaml.tmpl, internal/controller/modelregistry_controller.go
Add annotations for external service host and port in k8s MR service
Fixes RHOAIENG-11092
Tested istio and non-istio samples to look for annotations being set correctly in istio sample only.
=> feat: add annotations for external service host and port in MR service, fixes RHOAIENG-11092

config/samples/mysql/mysql-db.yaml, config/samples/postgres/postgres-db.yaml
Added missing DB labels in DB secrets, without which sample DB cannot be deloyed using a label filter.
Fixes RHOAIENG-12126
Used the following command in a new namespace to create a test DB:
```shell
oc apply -k config/samples/secure-db/mysql/ -l app.kubernetes.io/name=model-registry-db
```
=> fix: add missing DB labels in DB secrets, fixes RHOAIENG-12126

Dockerfile
Switched from `go build` to `make build` in the Dockerfile, also I have added the minimal needed COPY to make the command work, also I had to switch to USER root to make sed work, as I had the following error:
```
sed "s|quay.io/opendatahub/model-registry:.*|quay.io/opendatahub/model-registry:latest|" -i ./config/manager/manager.yaml
sed: couldn't open temporary file ./config/manager/sedmgPg4K: Permission denied
```
(solved by following this issue https://github.com/containers/podman/issues/5197)
run `make docker-build` locally
=> feat: switch from go build to make build in dockerfile

cmd/main.go, config/manager/manager.yaml, config/overlays/odh/kustomization.yaml, config/overlays/odh/patches/manager_auth_config_patch.yaml, internal/controller/modelregistry_controller.go
ODH operator writes authorino auth config to a configmap auth-refs in the same namespace as the odh component operators
Set authorino config properties in odh overlay from this configmap
Fixes RHOAIENG-5076
Tested by creating operator image locally and using the ODH overlay to test whether configmap properties are injected and used correctly in the operator for a model registry with the yaml:
```yaml
apiVersion: modelregistry.opendatahub.io/v1alpha1
kind: ModelRegistry
metadata:
annotations:
labels:
app.kubernetes.io/created-by: model-registry-operator
app.kubernetes.io/instance: modelregistry-sample
app.kubernetes.io/managed-by: kustomize
app.kubernetes.io/name: modelregistry
app.kubernetes.io/part-of: model-registry-operator
name: modelregistry-sample
namespace: odh-model-registries …
```
=> feat: set authorino config properties in odh overlay from odh operator configmap auth-refs, fixes RHOAIENG-5076

api/v1alpha1/modelregistry_types.go, config/crd/bases/modelregistry.opendatahub.io_modelregistries.yaml
General cleanup optional properties
Fixes RHOAIENG-12838
=> fix: cleanup optional properties, fixes RHOAIENG-12838

api/v1alpha1/modelregistry_annotations.go, api/v1alpha1/modelregistry_types.go, api/v1alpha1/modelregistry_webhook.go, config/crd/bases/modelregistry.opendatahub.io_modelregistries.yaml, internal/controller/modelregistry_controller.go, internal/controller/modelregistry_controller_status.go
Moved runtime default property values to spec status field json string `specDefaults`
The field is primarily for diagnostics to be able to troubleshoot operator behavior.
The generated resources (Deployments, etc.) are not affected by this change. 
Fixes RHOAIENG-15033
Built and tested in local cluster, also existing envtest and CI tests should pass.
=> feat: moved runtime defaults to spec status, fixes RHOAIENG-15033

cmd/main.go, config/rbac/role.yaml, internal/controller/modelregistry_controller.go, internal/controller/modelregistry_controller_status.go
Add new reason `ConfigurationError` to `Available` condition by checking mlmd log
Fixes RHOAIENG-11328
Tested locally by using an invalid hostname for db, which causes the new reason to show up with mlmd log error message.
=> fix: add ConfigurationError reason to Available condition by checking mlmd log, fixes RHOAIENG-11328

api/v1alpha1/modelregistry_webhook.go, internal/controller/modelregistry_controller_status.go
Cleanup runtime default properties on first reconcile
Fixes RHOAIENG-15033
Tested locally by using an MR with default runtime properties and verified that it gets cleaned up to remove them.
Create test MR using secure-db mysql-tls sample, then delete the test MR and wait for it to be completely removed. 
Recreate the MR with default runtime properties using the command:
```shell
oc delete mr -n odh-model-registries modelregistry-sample
oc apply -f - <<EOF
apiVersion: modelregistry.opendatahub.io/v1alpha1
kind: ModelRegistry
metadata:
labels:
app.kubernetes.io/created-by: model-registry-operator
app.kubernetes.io/instance: modelregistry-sample
app.kubernetes.io/managed-by: kustomize
app.kubernetes.io/name: modelregistry
app.kubernetes.io/part-of: model-registry-operator
name: …
```
=> fix: cleanup runtime default properties on first reconcile, fixes RHOAIENG-15033

.github/workflows/build-image-pr.yml, .github/workflows/build.yml, Dockerfile, Makefile, config/manager/manager.yaml, config/overlays/odh/params.env, go.mod, internal/controller/config/defaults.go
analogous to https://github.com/opendatahub-io/model-registry-operator/pull/110 proceeding to merge for releasing 0.2.13
=> chore: change release image versions for v0.2.13

Makefile, config/component_metadata.yaml
Sync version in config/component_metadata.yaml with the image version from params.env
Only changes yaml file version property.
=> fix: sync version in config/component_metadata.yaml

docs/install.md
When these instructions were written, the DSC used for reference had a devFlag in place for overriding the dashboard manifests. This isn't necessary.
N/A, markdown-only change
=> Remove dashboard devFlag from docs/install.md

.github/workflows/build-image-pr.yml, .github/workflows/build.yml, go.mod
Bump Go version to 1.22.12 in order to fix the build. I'm extracting this from #194. 
Build and sanity check.
=> chore: bump go to 1.22.12

api/v1alpha1/modelregistry_types.go, api/v1alpha1/modelregistry_webhook.go, api/v1alpha1/modelregistry_webhook_test.go, cmd/main.go, config/crd/bases/modelregistry.opendatahub.io_modelregistries.yaml, config/overlays/odh/kustomization.yaml, config/overlays/odh/patches/manager_istio_config_patch.yaml, internal/controller/config/defaults.go, internal/controller/config/defaults_test.go, internal/controller/modelregistry_controller_test.go
Add env variables in operator to allow connecting to an external smcp and ingress gateway.
Tested manually by installing locally and applying local odh configuration generated with:
```shell
kustomize build config/overlays/odh
```
Generated odh overlay operator deployment uses env variables populated from odh operator configmap service-mesh-refs.
Verified that creating an MR with the new operator produces the following in the spec defaults:
```yaml
,"gateway":{"controlPlane":"data-science-smcp","domain":"apps.rosa.dbokde-cluster.2rkm.p3.openshiftapps.com","istioIngress":"ingressgateway"}}
```
Note that the ingress gateway odh configmap property is optional, as an update is needed in ODH operator to pass that information to the MR operator in the future. The MR operator sets the value to …
=> fix: make istio ingress gateway and control plane properties environment variables, to support external smcp, fixes RHOAIENG-19912

internal/controller/config/templates/istio/gateway.yaml.tmpl, internal/controller/modelregistry_controller.go, internal/controller/modelregistry_controller_test.go
The label `maistra.io/owner-name` isn't propagated from the deployment to the pod `istio-ingressgateway`, so the selector failed in the istio Gateway, we choose to switch to the label `istio.io/rev` which is consistent across all related resources
tested on different clusters
=> fix(template): updated the gateway template label

.github/workflows/build-image-pr.yml, internal/controller/config/templates/deployment.yaml.tmpl
Apply the `securityContext` settings from upstream PR [#768](https://github.com/kubeflow/model-registry/pull/768). This sets seccompProfile, forbids containers to run as root, and disables unnecessary system calls.
Intended to satisfy [RHOAIENG-13857](https://issues.redhat.com/browse/RHOAIENG-13857).
Verified that the settings were applied and checked MR functionality.
=> feat: add securityContext to manifests

api/v1alpha1/modelregistry_webhook.go, api/v1alpha1/modelregistry_webhook_test.go, api/v1alpha1/webhook_suite_test.go, cmd/main.go, config/manager/manager.yaml, config/overlays/odh/params.env, config/overlays/odh/replacements.yaml, internal/controller/config/defaults.go, internal/controller/config/defaults_test.go
Validate registry namespace if a default namespace is set in the env variable REGISTRIES_NAMESPACE
Fixes RHOAIENG-20962
Added unit tests for env variable and webhook
=> feat: validate registry namespace if a default namespace is set, fixes RHOAIENG-20962

.github/workflows/build-image-pr.yml, internal/controller/config/templates/deployment.yaml.tmpl
Remove fixed runAsUser and runAsGroup
Fix Kind cluster testing to set missing ids in mlmd image for now
Fixes RHOAIENG-21954
CI should validate Kind patch, removing ids was tested manually in OpenShift
=> fix: remove fixed runAsUser and runAsGroup, fixes RHOAIENG-21954

.github/workflows/build-image-pr.yml
Removes the work-around to allow the tests to work in Kind now that the image includes a `USER` directive.
Automated tests in the PR.
=> chore: remove work-around for missing user in mlmd image

internal/controller/suite_test.go, internal/utils/io.go
The old file was [removed](https://github.com/openshift/api/pull/2268/files#diff-a8396022e5cbcaddf0147a4917b3f1e4c1ee21f32e053c96bff72d83a0c33192).
Running the tests
=> fix: use a new URL for the route.openshift.io/v1 CRD
